### ISSUE TITLE
merge into opscode-cookbooks/chef-client

### ISSUE THREAD

**Issue by josephholsten** [hw-cookbooks/omnibus_updater#28]
chef-client has a [ticket (COOK-3155)](http://tickets.opscode.com/browse/COOK-3155) to add the feature set of omnibus_updater. And there's a [pull request](https://github.com/opscode-cookbooks/chef-client/pull/102) that provides some of that functionality (but without any tests).

I'd really like to see this codebase just become the one in chef-client. Interested?

**Comment by jtimberman** [comment]
Fwiw, the ability for chef to upgrade itself is going to be built in per [this RFC](https://github.com/chef/chef-rfc/blob/614353e05c7b8825bfceed48bfc8c86d0c25a0d8/rfc070-chef-upgrade.md).
